Use ScuolaDB
GO
-- Select selezion, select @version o select@servername
SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME

-- SE SOLO UNA COLONNA
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME

--
CREATE PROCEDURE sp_GetAllTabelNames
AS
BEGIN
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'BASE TABLE'
    ORDER BY TABLE_NAME
END
GO

EXEC sp_GetAllTabelNames;